### ISSUE TITLE
ESMTP

### ISSUE THREAD

**Issue by bablukid** [benmerckx/smtpmailer#2]
When using smtpmailer against OVH smtp servers ( OVH is the most famous web hosting company in france ), I get errors ("Server does not support auth login
") because OVH server doesnt reply "ESMTP" when the connection is done, even if it supports ESMTP.
```
SmtpMailer.hx:222:    <<<220 ssl0.ovh.net player739
SmtpMailer.hx:200: >>>EHLO vagrant-ubuntu-trusty-64
SmtpMailer.hx:222:    <<<250-player739.ha.ovh.net
SmtpMailer.hx:222:    <<<250-SIZE 104850000
SmtpMailer.hx:222:    <<<250-AUTH PLAIN LOGIN
SmtpMailer.hx:222:    <<<250-AUTH=PLAIN LOGIN
SmtpMailer.hx:222:    <<<250-ENHANCEDSTATUSCODES
SmtpMailer.hx:222:    <<<250 8BITMIME
SmtpMailer.hx:200: >>>AUTH LOGIN
```

Since the ESMTP RFC has been published in 1995, should'nt we consider that all current smtp servers are EMSTP compatible ?

why not just send "EHLO" by default ? ( https://github.com/benmerckx/smtpmailer/blob/master/src/smtpmailer/SmtpMailer.hx#L141 )

It seems anyway that the lib cannot handle the situation where ESMTP is not available.

**Comment by benmerckx** [comment]
We could indeed default to EHLO if auth is given in the options as it's part of esmtp, and wouldn't work with HELO anyway.
