### ISSUE TITLE
UTF8 encoded html content

### ISSUE THREAD

**Issue by varadig** [benmerckx/smtpmailer#4]
I wanted to send html content which is contains unicode characters, like this:
_A regisztráció véglegesítéséhez kérjük_

but when the mail is arrived I got this:
_A regisztrรA1ciรB3 vรA9glegesรADtรA9sรA9hez kรA9rjรBCk_

**Comment by benmerckx** [comment]
Which target are you using to send mails?

**Comment by varadig** [comment]
Nodejs.
first i thinked, the smtp provider was the problem, but
I tried send mail with [nodemailer](https://nodemailer.com/about/), with the same smtp provider, and the encoding was ok.

**Comment by benmerckx** [comment]
This should be fixed when sending text in d4c1c03. I've put out a new release, 0.4.0.

**Comment by varadig** [comment]
Thanks, I will check!
