### ISSUE TITLE
Update to latest tink stack

### ISSUE THREAD

**Issue by kevinresol** [benmerckx/smtpmailer#6]
Because the `pure` branch has been merged back into master.

But I think there are some bugs in `StreamParser` which might be not so easy to fix.

**Comment by postite** [comment]
smtpmailer is completely broken with tink(pure) io , streams...

**Comment by kevinresol** [comment]
@postite I just made a few changes. Can you try the `pure` branch?

**Comment by kevinresol** [comment]
I only realize just now I don't have access to this repo and was only pushing to my fork so far (lol). @postite you can try the branch in #10
